---
title: "190917_inclass"
author: "Gavin Ko"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(haven)
```

```{r geting_directory}
## there's two ways: absolute directory(path), person specific
## relative path: direction starting from places familiar, main spots
## relative path is strongly recommended
getwd()

```

```{r load in a dataset}
litters_data = read_csv(file = "./FAS_litters.csv")

#clean up the names with janitor package
litters_data = janitor :: clean_names(litters_data)

```

```{r inclass practice I}
Pupsdata_absolute = read_csv(file = "D:\\Desktop\\Courses\\P8105_Data Science\\Coding\\190917_DS_Coding\\190917inclass_data-wrangling\\FAS_pups.csv")
Pupsdata_relative = read_csv(file = "FAS_pups.csv")

```

```{r descriptive summary}
#a slick tool that allows better summary
skimr::skim(litters_data)

```

```{r adding variable to read funtion}
#skipping first 10 rows, and remove the column names
litters_data_skipping = read_csv(file = "FAS_litters.csv", skip = 10, col_names = F)

```
R would automatically attribute the data to some sort of data class. But, you're allowed to overwrite it. 

```{r change variable types}
# in R, spaces and special character won't be recognized as col names.
litters_data = read_csv(file = "FAS_litters.csv",
  col_types = cols(
    'Group' = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
    )
  )
```

```{r read excel file}
# remember that in readxl, use 'path = ' rather than 'file = '
# You can specifiy the range of data included
MLB_data = read_excel(path = "mlb11.xlsx",
                      range = "A1:D7")

```

```{r read SAS file}
pulse_data = read_sas("public_pulse_data.sas7bdat")

```

```{r output csv file}
write_csv(MLB_data, "mlb_subset.csv")

```


