---
title: "190924_inclass"
author: "Gavin Ko"
date: "9/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r install the new version of tidyr}
install.packages("tidyr")
```

```{r read data}
pulse_data = haven::read_sas("public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

```{r wide to long}
pivot_longer(pulse_data, 
             bdi_score_bl : bdi_score_12m,
             names_to = "visit",
             values_to = "bdi")
```

pivot longer once got it name as "gather", not anymore.

```{r put all of this together}
pulse_data = haven::read_sas("public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
    pivot_longer(bdi_score_bl : bdi_score_12m,
                 names_to = "visit",
                 names_prefix = "bdi_score_",
                 values_to = "bdi"
    ) %>% 
    mutate(
      visit = recode(visit, "b1" = "00m")
    ) %>% view

```

Now, let's move on to next dataframe.

```{r litter data}
litters_data = 
  read_csv("FAS_litters.csv") %>% 
  janitor :: clean_names() %>% 
  separate(col = group, into = c("dose", "dat_of_tx"), 3) %>% 
  mutate(  
    dose = str_to_lower(dose)
)

```

How about untidy the data into human readible form?

```{r create data frame}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
```

```{r widen the data}
pivot_wider(analysis_result,
  names_from = time,
  values_from = mean
)

```

Lord of the rings!

```{r read in data}
fellowship_ring = 
  readxl::read_excel("LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```
```{r lotr tidy}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") %>% 
  mutate(race = str_to_lower(race)) %>% 
  select(movie, race, sex, words)
```
# Joint data example

```{r}
pup_data = 
  read_csv("FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
#left joint: care about all things on the left
#assign multiple variable sorting using by = c ("a", "b", ...)
fas_data

#full_join keeps everything, inner_join keeps that both fits
#cannot joint more than two datasets at a time

```

